package:
  name: mt-ext-proc-grpc
  epoch: 2
  version: e1747fb-dirty
  description: Example Envoy ext_proc
  url: https://github.com/mt-inside/TODO
  copyright:
    - paths:
        - "*"
      license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - build-base
      - pkgconf
      # Need rustup rather than rust, because we want nightly, and rust package doesn't include rustup toolchain manager
      # rustup contains rustup-init; indeed they're different invocations of the same binary
      - rustup
      - just
      - git
pipeline:
  - name: Build
    runs: |
      git config --global --add safe.directory /home/build
      rustup-init --default-toolchain nightly -y # Calling this as "rustup toolchain install stable" doesn't make the ~/.cargo links (even after setting default toolchain)
      source "$HOME/.cargo/env"
      just tools-install-build-ci
      just build-ci
      mkdir -p "${{targets.destdir}}/usr/bin"
      mv "./target/release/mt-ext-proc-grpc" "${{targets.destdir}}/usr/bin/mt-ext-proc-grpc"
